language: swift
osx_image: xcode8.1
podfile: Example/Podfile

before_install:
  - pod repo update --silent

script:
  - xcodebuild -workspace Example/Example.xcworkspace -scheme Example -sdk iphonesimulator -destination 'name=iPhone 7' -enableCodeCoverage YES test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -J RepositoryKit